= Antora Default UI
// Settings:
:experimental:
:hide-uri-scheme:
// Project URLs:
:url-project: https://gitlab.com/librepcb/librepcb-docs-ui
:img-ci-status: {url-project}/workflows/bundle/badge.svg
// External URLs:
:url-antora-docs: https://docs.antora.org
:url-git: https://git-scm.com
:url-git-dl: {url-git}/downloads
:url-opendevise: https://opendevise.com
:url-nodejs: https://nodejs.org
:url-librepcb: https://github.com/librepcb

image:{img-ci-status}[CI Status (GitHub Actions)]

This is the source for the LibrePCB Antora UI template.

== Development Quickstart

This section offers a basic tutorial to teach you how to set up the project,
preview it locally, and bundle it.

A more comprehensive guide can be found in the Antora documentation at
{url-antora-docs}.

=== Prerequisites

To preview and bundle the UI, you need the following software on your computer:

* {url-git}[git] (command: `git`)
* {url-nodejs}[Node.js] (commands: `node` and `npm`)

==== git

First, make sure you have git installed.

 $ git --version

If not, {url-git-dl}[download and install] the git package for your system.

==== Node.js

Next, make sure that you have Node.js installed (which also provides npm).

 $ node --version

If this command fails with an error, you don't have Node.js installed.
If the command doesn't report an LTS version of Node.js (e.g., v10.15.3), it
means you don't have a suitable version of Node.js installed.

You have the option to install it from {url-nodejs}[Node.js website].

=== Clone and Initialize the UI Project

Clone the project using git:

[subs=attributes+]
 $ git clone {url-project} &&
   cd "`basename $_`"

Stay in this project folder when executing all subsequent commands.

Use npm to install the project's dependencies inside the project.
In your terminal, execute the following command:

 $ npm install .

=== Preview the UI

The default UI project is configured to preview offline. The files in the
[.path]_preview-src/_ folder provide the sample content that allow you to see
the UI in action.

In this folder, you will primarily find pages written in AsciiDoc. These provide
a representative sample and kitchen sink of content from the real site.

To build the UI and preview it in a local web server, run the `preview` command:

 $ npm run preview

You'll see a URL listed in the output of this command:

....
[12:00:00] Starting server...
[12:00:00] Server started http://localhost:5252
[12:00:00] Running server
....

Navigate to this URL to preview the site locally.

While this command is running, any changes you make to the source files will be
instantly reflected in the browser. This works by monitoring the project for
changes, running the `preview:build` task if a change is detected, and sending
the updates to the browser.

Press kbd:[Ctrl+C] to stop the preview server and end the continuous build.

=== Package for Use with Antora

If you need to package the UI so you can use it to generate the documentation
site locally, run the following command:

 $ npm run bundle

If any errors are reported by lint, you'll need to fix them.

When the command completes successfully, the UI bundle will be available at
[.path]_build/ui-bundle.zip_. You can point Antora at this bundle using the
`--ui-bundle-url` command-line option.

The UI bundle will again be available at [.path]_build/ui-bundle.zip_.

== Copyright and License

Copyright (C) 2017-2019 OpenDevise Inc., the Antora Project and the LibrePCB
Project.

Use of this software is granted under the terms of the
https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0]
(MPL-2.0). See link:LICENSE[] to find the full license text.

== Authors

Development of Antora is led and sponsored by {url-opendevise}[OpenDevise Inc].

This template variant is developed by {url-librepcb}[LibrePCB].
