name: Bundle ZIP
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install, build, and test
        run: |
          npm ci
          npm run bundle
        env:
          CI: true
      - uses: actions/upload-artifact@v1
        with:
          name: bundle
          path: build/ui-bundle.zip
